image: 
  name: cirrusci/flutter

stages:
- coverage
- publish

code_analyze:
  stage: coverage
  dependencies: []
  script:
    - flutter analyze

#test:
#  stage: coverage
#  dependencies: []
#  script:
#    - flutter test

build_web:
  stage: coverage
  image: cirrusci/flutter:beta
  script:
    - flutter config --enable-web
    - flutter build web --release
  artifacts:
    paths:
      - build/web/


build_android_fdroid:
  stage: coverage
  script:
    - cd android && echo $FDROID_KEY | base64 --decode --ignore-garbage > key.jks && cd ..
    - cd android && echo "storePassword=${FDROID_KEY_PASS}" >> key.properties && cd ..
    - cd android && echo "keyPassword=${FDROID_KEY_PASS}" >> key.properties && cd ..
    - cd android && echo "keyAlias=key" >> key.properties && cd ..
    - cd android && echo "storeFile=../key.jks" >> key.properties && cd ..
    - flutter build apk --release
  artifacts:
    when: on_success
    paths:
      - build/app/outputs/apk/release/app-release.apk
  only:
    - master

build_android_debug:
  stage: coverage
  script:
    - flutter build apk --debug
  artifacts:
    when: on_success
    paths:
      - build/app/outputs/apk/release/app-debug.apk
  except:
    - master

pages:
  stage: publish
  image: ruby:2.3
  script:
    - rm assets -r
    - cp _config.yml ./build/web/
    - cp Gemfile ./build/web/
    - cp Gemfile.lock ./build/web/
    - cd build/web/ && bundle install && cd ../../
    - cd build/web/ && bundle exec jekyll build -d public && cd ../../
    - mv build/web/public ./
  dependencies:
    - build_web
  artifacts:
    paths:
      - public
  only:
    - master
