include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    - avoid_print
    - constant_identifier_names
    - prefer_final_locals
    - prefer_final_in_for_each
    - sort_pub_dependencies

analyzer:
  errors:
    todo: ignore
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/l10n/*.dart
