name: fluffychat
description: Chat with your friends.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.21.1+48

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  famedlysdk:
    git:
      url: https://gitlab.com/famedly/famedlysdk.git
      ref: 66572bd03209c1c6488cde53a0c72c11faef341d

  localstorage: ^3.0.3+6
  file_picker_cross: 4.2.2
  image_picker: ^0.6.7+12
  url_launcher: ^5.7.8
  cached_network_image: ^2.3.3
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.1
  # desktop_notifications: ^0.0.0-dev.4  // Currently blocked by: https://github.com/canonical/desktop_notifications.dart/issues/5
  matrix_link_text: ^0.3.2
  path_provider: ^1.6.22
  downloads_path_provider_28: ^0.1.0
  permission_handler: ^5.0.1+1
  webview_flutter: ^1.0.5
  share: ^0.6.5+4
  flutter_secure_storage: ^3.3.5
  http: ^0.12.2
  universal_html: ^1.2.3
  receive_sharing_intent: ^1.4.1
  flutter_slidable: ^0.5.7
  photo_view: ^0.10.2
  flutter_sound: 2.1.1
  open_file: ^3.0.3
  mime_type: ^0.3.2
  bot_toast: ^3.0.4
  flutter_matrix_html: ^0.1.10
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.2.0
  sqlite3: ^0.1.7
  random_string: ^2.1.0
  flutter_typeahead: ^1.8.8
  flutter_olm: ^1.0.1
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  circular_check_box: ^1.0.4
  flutter_localizations:
    sdk: flutter
  sqflite: ^1.3.2 # Still used to obtain the database location
  native_imaging:
    git:
      url: https://gitlab.com/famedly/libraries/native_imaging.git
      ref: master
  flutter_blurhash: ^0.5.0
  sentry: ">=3.0.0 <4.0.0"
  scroll_to_index: ^1.0.6
  swipe_to_action: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.4"
  pedantic: ^1.9.2
  dapackages: ^1.3.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Adds code generation (synthetic package) support
  generate: true


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
