name: fluffychat
description: Chat with your friends.
publish_to: none
version: 0.31.0+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  adaptive_dialog: ^0.10.0+5
  adaptive_page_layout: ^0.2.4
  adaptive_theme: ^2.2.0
  android_path_provider: ^0.2.1
  audioplayers: ^0.18.3
  cached_network_image: ^3.0.0
  cupertino_icons: any
  desktop_notifications: ^0.4.0
  email_validator: ^2.0.1
  emoji_picker_flutter: ^1.0.5
  famedlysdk:
    git:
      url: https://gitlab.com/famedly/famedlysdk.git
      ref: main
  fcm_shared_isolate:
    git:
      url: https://gitlab.com/famedly/libraries/fcm_shared_isolate.git
      ref: main
  file_picker_cross: ^4.3.2
  flutter:
    sdk: flutter
  flutter_app_lock: ^1.5.0
  flutter_blurhash: ^0.6.0
  flutter_cache_manager: ^3.0.1
  flutter_local_notifications: ^5.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_matrix_html: ^0.3.0
  flutter_olm: ^1.1.1
  flutter_openssl_crypto: ^0.0.1
  flutter_secure_storage: 3.3.5 # Do not upgrade or this will break Linux builds!
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.21.0+1
  flutter_typeahead: ^3.1.1
  future_loading_dialog: ^0.1.2
  image_picker: ^0.7.4
  intl: any
  localstorage: ^4.0.0+1
  mime_type: ^1.0.0
  moor: ^4.2.1
  native_imaging:
    git:
      url: https://gitlab.com/famedly/libraries/native_imaging.git
      ref: master
  open_file: ^3.2.0
  open_noti_settings: ^0.1.0
  package_info: ^2.0.0
  path_provider: ^2.0.1
  permission_handler: ^6.1.3
  pin_code_text_field: ^1.8.0
  provider: ^5.0.0
  receive_sharing_intent: ^1.4.5
  record: ^2.1.1
  scroll_to_index: ^2.0.0
  sentry: ^5.0.0
  share: ^2.0.1
  sqflite: ^2.0.0+3 # Still used to obtain the database location
  sqlite3: ^1.0.0
  swipe_to_action: ^0.1.0
  uni_links: ^0.5.1
  unifiedpush: ^1.0.2
  universal_html: ^2.0.8
  url_launcher: ^6.0.3

dev_dependencies:
  dapackages: ^1.6.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  fonts:
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans/NotoSans-Regular.ttf
        - asset: fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
        - asset: fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
