name: fluffychat
description: Chat with your friends.
publish_to: none
version: 0.29.1+0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  famedlysdk:
    git:
      url: https://gitlab.com/famedly/famedlysdk.git
      ref: main
  unifiedpush:
    git:
      url: https://github.com/UnifiedPush/flutter-connector.git
      ref: main
  fcm_shared_isolate:
    git:
      url: https://gitlab.com/famedly/libraries/fcm_shared_isolate.git
      ref: main
  cupertino_icons: any
  localstorage: ^4.0.0+1
  file_picker_cross: ^4.3.2
  image_picker: ^0.7.4
  url_launcher: ^6.0.3
  cached_network_image: ^3.0.0
  flutter_local_notifications: ^5.0.0+1
  adaptive_page_layout: ^0.2.3
  provider: ^5.0.0
  adaptive_theme: ^2.2.0
  # desktop_notifications: ^0.0.0-dev.4  // Currently blocked by: https://github.com/canonical/desktop_notifications.dart/issues/5
  path_provider: ^2.0.1
  android_path_provider: ^0.2.1
  permission_handler: ^6.1.3
  share: ^2.0.1
  flutter_secure_storage: ^4.1.0
  universal_html: ^2.0.8
  receive_sharing_intent: ^1.4.5
  flutter_slidable: ^0.6.0
  flutter_sound_lite: ^8.1.1
  open_file: ^3.2.0
  mime_type: ^1.0.0
  adaptive_dialog: ^0.10.0+5
  flutter_matrix_html: ^0.3.0
  moor: ^4.2.1
  sqlite3: ^1.0.0
  sqflite: ^2.0.0+3 # Still used to obtain the database location
  flutter_typeahead: ^3.1.1
  flutter_olm: ^1.1.1
  flutter_openssl_crypto: ^0.0.1
  intl: any
  circular_check_box: ^1.0.4
  flutter_localizations:
    sdk: flutter
  native_imaging:
    git:
      url: https://gitlab.com/famedly/libraries/native_imaging.git
      ref: master
  flutter_blurhash: ^0.6.0
  sentry: ^5.0.0
  scroll_to_index: ^2.0.0
  swipe_to_action: ^0.1.0
  flutter_svg: ^0.21.0+1
  flutter_cache_manager: ^3.0.1
  open_noti_settings: ^0.1.0
  emoji_picker_flutter: ^1.0.3
  future_loading_dialog: ^0.1.2
  package_info: ^2.0.0
  flutter_app_lock: ^1.5.0
  flutter_screen_lock: ^4.0.3
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
  dapackages: ^1.6.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  fonts:
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans/NotoSans-Regular.ttf
        - asset: fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
        - asset: fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
