# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FluffyChat Official Website
email: christian-pauly@posteo.de
description: Official Website of FluffyChat
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://fluffychat.im" # the base hostname & protocol for your site
gitlab_username:  christianpauly

# Build settings
markdown: kramdown
languages: [ "en", "de", "es", "hr", "nl", "ru", "tr" ]
exclude_from_localizations: ["assets"]
exclude: [ "README.md", "LICENSE"]
assets: "/assets"
