name: fluffychat
version: 0.1.0
summary: Chat with your friends.
description: Chat with your friends.
icon: assets/logo.png
confinement: strict
base: core18
grade: stable

apps:
  fluffychat:
    command: fluffychat
    extensions: [flutter-dev]
    plugs:
    - network
    - home

parts:
  olm:
    source: .
    source-type: git
    plugin: cmake
    build-packages:
    - build-essential
    override-build: |
      rm -r olm
      git clone https://gitlab.matrix.org/matrix-org/olm.git
      cd olm
      cmake . -Bbuild
      cmake --build build
      sudo make install
  fluffychat:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    stage-packages:
    - libsqlite3-0
    override-build: sudo apt install libolm3
    after: [olm]
