name: fluffychat
base: core18
version: script
summary: Open. Nonprofit. Cute ♥
description: |
  FluffyChat - Chat with your friends
  
  9 greatest FluffyChat features:
  1. Opensource and open development where everyone can join.
  2. Nonprofit - FluffyChat is donation funded.
  3. Cute design and many theme settings including a dark mode.
  4. Unlimited groups and direct chats.
  5. FluffyChat is made as simple to use as possible.
  6. Free to use for everyone without ads.
  7. FluffyChat can use your addressbook to find your friends or you can use
  usernames.
  8. There is no "FluffyChat server" you are forced to use. Use the server
  you find trustworthy or host your own.
  9. Compatible with Riot, Fractal, Nekho and all matrix messengers.
  
  Join the community: fluffychat://+ubports_community:matrix.org
  Website: http://fluffy.chat
  Microblog: https://metalhead.club/@krille

grade: devel
icon: assets/logo.png
confinement: devmode

parts:
  olm:  # FIXME
    source: https://gitlab.matrix.org/matrix-org/olm.git
    source-type: git
    source-tag: 3.2.1
    plugin: cmake
    build-packages:
    - build-essential
    override-build: |
      cd /root/parts/olm/src
      cmake . -Bbuild
      cmake --build build
  fluffychat:
    after: [olm]
    plugin: dump
    source: ./build/linux/release/bundle
    stage-packages:
      - libsqlite3-dev

slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: chat.fluffy.fluffychat

apps:
  fluffychat:
    command: fluffychat
    extensions:
      - gnome-3-28
    plugs:
      - network
      - home
    slots:
      - dbus-svc
